config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :answers
  resources :questions
  devise_for :users
  root 'home#index'
  get 'home/about'
  get 'home/team'
  get 'home/error404'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # config/routes.rb
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end 
  put '/increment/:id/', to: "increment#increment_votes", as: 'increment'
  match '/404', to: 'home#error404', via: :all
end

app/models/question.rb
class Question < ApplicationRecord
    validates :content, :tag, presence: true
    has_many :answer, dependent: :destroy
    belongs_to :user

    def self.search(search)
        if search
            where(["tag LIKE ?","%#{search.humanize}%"]).order(:updated_at).reverse_order
        else
            all.order(:updated_at).reverse_order
        end
    end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]

  # GET /questions or /questions.json
  def index
    # @questions = Question.all
    @questions = Question.search(params[:search])
    if @questions.blank?
      flash[:alert] = "No Questions found, It would be great if you post one."
    else
      flash[:alert] = nil
    end
  end

  # GET /questions/1 or /questions/1.json
  def show
    if params[:search].present?
      redirect_to questions_path(:search => params[:search], :commit => "search")
    end
  end

  # GET /questions/new
  def new
    if params[:search].present?
      redirect_to questions_path(:search => params[:search], :commit => "search")
    else
      flash[:alert] = nil
    end
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    if params[:search].present?
      redirect_to questions_path(:search => params[:search], :commit => "search")
    else
      flash[:alert] = nil
    end
    if current_user.id != @question.user_id
      redirect_to @question, alert: "Not Authorized User"
    end
    @a = Answer.find_by(question_id: @question.id)
    if @a.inspect.length > 28
      redirect_to @question, alert: "Question has already been answered, so can't be edited."
    end
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    if current_user.id == @question.user_id
      respond_to do |format|
        if @question.update(question_params)
          format.html { redirect_to @question, notice: "Question was successfully updated." }
          format.json { render :show, status: :ok, location: @question }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @question, alert: "Not Authorized User"
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    if current_user.id == @question.user_id
      @question.destroy
      respond_to do |format|
        format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to @question, alert: "Not Authorized User"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      if Question.find_by(id: params[:id]).blank?
        redirect_to controller: 'home', action: 'error404'
      else
        @question = Question.find(params[:id]) 
      end
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:content, :tag, :user_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="container">
  <%= form_with(model: question) do |form| %>
    <% if question.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          <% question.errors.each do |error| %>
          <div><%= error.full_message %></div>
        <% end %>
        </div>
      </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :content, 'Question Content' %>
      <%= form.text_area :content, class:'form-control' %>
    </div>

    <div class="field form-group">
      <%= form.label "Select tag" %>
      <%= form.select :tag, %w[C++ Java Ruby JS Sql Postgres Others]%>
    </div>

    <div class="field">
      <% form.label :user_id %>
      <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
    </div> 

    <div class="actions">
      <%= form.submit 'Publish Question', class:'btn btn-default btn-box btn-blue' %>
      <%= link_to 'Back', questions_path, class:'btn btn-warning btn-orange btn-box' %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<% content_for :header do %>
    <title>Update Question - Queue Overflow</title>
<% end %>

<div class="container">
  <h3>Update this Question</h3><hr>
</div>
<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<% content_for :header do %>
    <title>All Questions - Queue Overflow</title>
<% end %>

<div class="container">
  <h3>All Questions
  <%= link_to 'Ask Question', new_question_path, class:'btn btn-default btn-box btn-blue pull-right', style:'margin-top:-10px;' %>
  </h3><hr>
  <% @questions.each do |question| %>
    <div class="box" style='padding:5px;margin:5px;border-bottom:0.5px solid lightgray;'>
    <div class="row">
      <div class="col-xs-2"><br>
        <h2><%= "#{Answer.where(question_id: question.id).count}" %></h2>
        <h5>Ans</h5>
      </div>
      <div class="col-xs-10 text-left"><br>
        <%= link_to question do %>
          <h4 class='text-left q-text'><i class="fa fa-hand-o-right"></i> <%= question.content %></h4>
        
        <% end %>
          <p>tag : <span class="btn btn-default btn-xs"><%= "#{question.tag}" %></span></p>
          <p class="text-left">
            <%= link_to "Open in new tab", question, class:'btn btn-info btn-xs', 'target': '_blank' %>
            <% if user_signed_in? && current_user.id == question.user_id %>
              <% if Answer.find_by(question_id: question.id).blank? %>
                <%= link_to 'Edit', edit_question_path(question), class:'btn btn-default btn-xs' %>
              <% end %>
              <%= link_to 'Delete this question', question, class:'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
        <p class='pull-right'>
          <i style='font-size:12px;'>
            Published By - <%= User.find(question.user_id).name %>,
            <%= time_ago_in_words question.created_at %> ago
          </i>
        </p>
      </div>
    </div>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<% content_for :header do %>
    <title>Ask a Question - Queue Overflow</title>
<% end %>
<div class="container">
  <h3>Ask a Public Question</h3><hr>
</div>


<%= render 'form', question: @question %>

app/views/questions/show.html.erb
<% content_for :header do %>
    <title><%= @question.content %> - Queue Overflow</title>
<% end %>

<div class="container">
  <style>
    .btn-back{
      border-radius: 50%;
    }
  </style>
  <%= link_to questions_path, class:'btn btn-default btn-md btn-back', title:'Go Back' do %>
    <i class="fa fa-arrow-left"></i>
  <% end %>
  <h3><i class="fa fa-hand-o-right"></i> <%= @question.content %></h3>
  <%= link_to 'Ask Question', new_question_path, class:'btn btn-default btn-box btn-blue pull-right' %> <br>
  Tags: <span class="btn btn-default btn-xs"><%= @question.tag %></span>
  <p>
    <i style='font-size:12px;'>
      Published By - <%= User.find(@question.user_id).name %>,
      <%= time_ago_in_words @question.created_at %> ago
    </i>
  </p>

  <% if user_signed_in? && current_user.id == @question.user_id && Answer.find_by(question_id: @question.id).blank? %>
    <%= link_to 'Edit', edit_question_path(@question), class:'btn btn-default btn-xs' %>
    <%= link_to 'Delete this question', @question, class:'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <hr>
  <% @a = Answer.where(question_id: @question.id).order(:up_vote).reverse_order %>
  <% if @a.inspect.length > 28 %>
    <% @a.each do |answer| %>
    <div class="row">
      <div class="col-xs-1 text-center">
        <%= link_to  increment_path(answer,'up_vote'), method: :put do %>
          <i class="fa fa-caret-up vote-icon"></i>
        <% end %>
        <br>
        <i class="fa fa-arrow-up"></i> <%= answer.up_vote %>
        <i class="fa fa-arrow-down"></i> <%= answer.down_vote %>
        <br>
        <%= link_to  increment_path(answer,'down_vote'), method: :put do %>
          <i class="fa fa-caret-down vote-icon"></i>
        <% end %>
      </div>
      <div class="col-xs-11">
        <div class="box" style='padding:5px;margin:5px;border-bottom:0.5px solid lightgray;'>
          <p class="text-left ans-text">
          <%= answer.content %>
          <br><br>
          <% if user_signed_in? && current_user.id == answer.user_id  %>
            <td><%= link_to 'Edit', edit_answer_path(answer, question: @question.id), class:'btn btn-default btn-xs' %></td>
            <td><%= link_to 'Delete this answer', answer, class:'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end  %>
        </p>
        <p class='pull-right'>
          <i style='font-size:12px;'>
            Published By - <%= User.find(answer.user_id).name %>,
            <%= time_ago_in_words answer.created_at %> ago
          </i>
        </p><br><br>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  <br><br>
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
      <%= link_to 'Give Your Answer', new_answer_path(:question => @question.id), class:'btn btn-default btn-box btn-blue btn-block' %>
    </div>
    <div class="col-sm-4"></div>
  </div>
</div>
<br><hr><br>