config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  resources :answers
  resources :questions
  devise_for :users
  root 'home#index'
  get 'home/about'
  get 'home/team'
  get 'home/error404'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # config/routes.rb
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end 
  put '/increment/:id/', to: "increment#increment_votes", as: 'increment'
  match '/404', to: 'home#error404', via: :all
end

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice %>
    </div>
<% end  %>

<% if flash[:alert] %>
  <div class="alert alert-danger alert-dismissible fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%- flash.each do |name, msg| -%>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    <%- end -%>
  </div>
<%- end -%>

<!--
<% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= alert %>
    </div>
<% end  %>
-->

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="container text-center">
        <svg aria-hidden="true" class="native svg-icon iconLogoGlyphMd" width="25" height="25" viewBox="0 0 32 37"><path d="M26 33v-9h4v13H0V24h4v9h22z" fill="#BCBBBB"></path><path d="M21.5 0l-2.7 2 9.9 13.3 2.7-2L21.5 0zM26 18.4L13.3 7.8l2.1-2.5 12.7 10.6-2.1 2.5zM9.1 15.2l15 7 1.4-3-15-7-1.4 3zm14 10.79l.68-2.95-16.1-3.35L7 23l16.1 2.99zM23 30H7v-3h16v3z" fill="#F48024"></path></svg>
        <span class='box-heading'>Queue<b>Overflow</b>
    </div><i class='fa fa-minus'></i><br><br>
    &copy; QueueOverflow 2021<br>
    All Rights Researved<br>
    Designed & Developed by - <%= link_to "Team", home_team_path, class:'footer-link' %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default my-nav">
  <div class="container">
    <a class="navbar-brand" href="../">
      <svg aria-hidden="true" class="native svg-icon iconLogoGlyphMd" width="20" height="22" viewBox="0 0 32 37"><path d="M26 33v-9h4v13H0V24h4v9h22z" fill="#BCBBBB"></path><path d="M21.5 0l-2.7 2 9.9 13.3 2.7-2L21.5 0zM26 18.4L13.3 7.8l2.1-2.5 12.7 10.6-2.1 2.5zM9.1 15.2l15 7 1.4-3-15-7-1.4 3zm14 10.79l.68-2.95-16.1-3.35L7 23l16.1 2.99zM23 30H7v-3h16v3z" fill="#F48024"></path></svg>
      <span class='logo-title'>Queue<b>Overflow</b></span>
    </a>
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="glyphicon glyphicon-align-justify"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse my-collapse" id="myNavbar">
        <ul class="nav navbar-nav my-navbar-nav">
            <!--<li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class='fa fa-bars'></i></a>
              <ul class="dropdown-menu">
                <li><a href="#">Page 1-1</a></li>
                <li><a href="#">Page 1-2</a></li>
                <li><a href="#">Page 1-3</a></li>
              </ul>
            </li>-->
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", home_about_path %></li>
            <li><%= link_to "Team", home_team_path %></li>
            <li><%= link_to "Questions", questions_path %></li>
        </ul>
        <!--
        <ul class="nav navbar-nav navbar-right my-navbar-nav">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Page 1-1</a></li>
              <li><a href="#">Page 1-2</a></li>
              <li><a href="#">Page 1-3</a></li>
            </ul>
          </li>
        </ul>
        -->

        <form class="navbar-form navbar-right">
            <!--
            <div class="form-group">
                <input type="text" class="form-control txt-box" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default sub-btn"><span class='glyphicon glyphicon-search'></span></button>
            -->
            <% if !user_signed_in? %>
              <%= link_to "Log In", new_user_session_path, class:'btn btn-info nav-login-btn' %>
              <%= link_to "Sign Up", new_user_registration_path, class:'btn btn-info nav-signup-btn' %>
            <% else %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:'btn btn-danger nav-signup-btn' %>
            <% end %>
        </form>
        <form class="navbar-form navbar-right">
          <%= form_with(url: '/questions', class:'form-group', method: 'get', local: true) do |f| %>
            <%= f.text_field :search, class:"form-control txt-box", placeholder:"Search Question Tags"%>
            <%= f.submit "search", class:"btn btn-default"%>
          <% end %>
        </form>
    </div>
  </div>
</nav>